name: CI Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh ${{ steps.get_version.outputs.VERSION }} X86
        ./build.sh ${{ steps.get_version.outputs.VERSION }} ARM
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: TODO New Release.
        draft: true
        files: |
          eSDK_Huawei_Storage_Kubernetes_CSI_Plugin_${{ steps.get_version.outputs.VERSION }}_X86_64.zip
          eSDK_Huawei_Storage_Kubernetes_CSI_Plugin_${{ steps.get_version.outputs.VERSION }}_ARM_64.zip
