name: CI Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'
    - name: Build
      run: |
        chmod +x ./${{github.repository}}/build.sh
        ./${{github.repository}}/build.sh 4.5.0 X86
