name: CI Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'
    - name: Build
      run: |
        chmod +x ./build.sh
        ./build.sh 4.5.0 X86
        ls
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          eSDK_Huawei_Storage_Kubernetes_CSI_Plugin_V4.5.0_X86_64
